### PR TITLE
Prototype Link functionality

### PR DESCRIPTION
**Pull request by rneatherway**
I haven't quite got the hang of the UnionArgParser -- it doesn't accept `--link <path>` right now. I need to think a bit more about the various error modes as well. You don't have to merge yet, but I just wanted to show you what I was working on. Hopefully I'll have some more time next week to move this on more quickly.

### CODE REVIEW

**Comment by kjnilsson** [comment]
Looks fine. Could --link just be a boolean flag without a path? I think the parse supports that if the the DU case doesn't have any args.

**Comment by rneatherway** [comment]
I tried that at first, but if you look at fsharp.compiler.service. fsproj
for example you can use Link to build a project structure completely
different from the filesystem. It would be nice for a default to be the
same as the relative path perhaps, although I'm not sure how paths
containing .. would look in VS.

**Comment by rneatherway** [comment]
OK I've updated this with a bunch of tests. I think everything works. I found a bug with the pattern:

```
| Descendant "ProjectReference" (Attribute "Include" a) when a.Value = incl
```

which I used for `Compile` nodes as well. It only checks the first Descendant, so if you add another ProjectReference to your addProjectReference test (above the existing one) you'll find that it fails.

I'm not completely happy with the tests which hit the filesystem, I might rejig things to separate out the part of addFile that can create or copy files to keep things easier to test.

I had to comment out the `AssemblyInfo` target in `build.fsx` because of the `InternalsVisibleTo`. If we start doing releases we'll want to handle it another way I suppose, as it is most convenient to get the version number from there.

**Comment by kjnilsson** [comment]
great thanks looks fine - yes I'd like to avoid file based unit tests if we can but we can always revisit that later. I didn't see that this had been updated so pushed some refactorings I had done which broke this PR. I'll pull it down and merge it manually. My bad. :) Perhaps we should move this to fsproject or similar?

So how did the InternalsVisibleTo attribute break the build script?

**Comment by rneatherway** [comment]
No worries, yes let's move it over to fsprojects.

Build.fsx regenerates the Assemblyinfo.fs file every time, which overwrites
your internalsvisibleto change. I just stopped it regenerating it at all
for now, but it is useful for the version numbers. We could just regex it
or something. Not a big deal.

**Comment by kjnilsson** [comment]
I've done the merge - are you able to move it to fsprojects?

Could we amend the template that is used for generating the AssemblyInfo?

**Comment by kjnilsson** [comment]
re: the Descendants pattern - this behaviour was intended - perhaps it should be called FirstDescendant instead. Unless finding the last one would make more sense?

**Comment by kjnilsson** [comment]
actually ignore that last commend I see why it is bug now :) I'll fix that.

**Comment by rneatherway** [comment]
It looks like the way is for you (as it's your repo) to open an issue: https://github.com/fsprojects/FsProjectsAdmin/

**Comment by rneatherway** [comment]
I'm not sure about the AssemblyInfo. I'm sure we can find a way around it though.

**Comment by Krzysztof-Cieslak** [comment]
Just ping @forki here or on twitter to get project moved ;)

**Pull request merged**
