### PR TITLE
Upgrade libraries

### PR DESCRIPTION
**Pull request by alex-slynko**
It is buildable from Mac

### CODE REVIEW

**Comment by rneatherway** [comment]
This repository is basically dormant. I think that the features offered here are pretty much beaten by Forge: https://github.com/fsharp-editing/Forge

If you want to develop this tool further, I would be happy to give you commit access for you to take over, if @kjnilsson agrees.

**Comment by kjnilsson** [comment]
@rneatherway I have no objections. I'm not planning to do any more work on this repo.

**Comment by alex-slynko** [comment]
I am ok to moving to forge, I fixed this, because I used it previous time I done F#. 

Could you please add notice in README, that Forge should be used instead.

**Comment by rneatherway** [comment]
Done

**Pull request closed without merging**
